Nerunelli/reduction table
Nerunelli/asonika-admin pull request #12
Opened 2022-05-08 18:01 UTC by Nerunelli

2022-05-08 18:50 UTC, FerunelliW requested changes

2022-05-08 18:50 UTC, FerunelliW commented on src/data/measurement/units/effects.ts
> +  });
```suggestion
  const res = await api.post('/measurement/unit/', {
    ...camelToSnake(payload),
    group: payload.group.uuid,
  });
```

2022-05-08 18:50 UTC, FerunelliW commented on src/data/measurement/units/effects.ts
> +  });
```suggestion
  await api.put(`/measurement/unit/${payload.uuid}/`, {
    ...camelToSnake(payload),
    group: payload.group.uuid,
  });
```

2022-05-08 18:50 UTC, FerunelliW commented on src/data/measurement/units/effects.ts
> +  });
```suggestion
  const res = await api.post('/measurement/unit/', {
      ...camelToSnake(payload),
    group: payload.group.uuid,
  });
```

2022-05-08 18:50 UTC, FerunelliW commented on src/data/measurement/units/effects.ts
> +  });
```suggestion
  await api.put(`/measurement/unit/${payload.uuid}/`, {
    ...camelToSnake(payload),
    group: payload.group.uuid,
  });
```

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/index.tsx
> +export interface IRange {
Ты уверена, что они все опциональными должны быть?

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/index.tsx
> +      })),
```suggestion
      filteredUnits.map((el, i) => ({
        ...el,
        idx: i
      })),
```

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/index.tsx
> +    const newName = watch(`fields.${e.target.id}` as any);
Насколько я понимаю, watch создает подписку, а тебе нужно просто получить значение поля. Для этого не нужна подписка.

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/index.tsx
> +        group,
Опять же деструктуризация.

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/index.tsx
> +        filteredUnits[Number(e.target.id.split('.')[0])];
```suggestion
      const data = filteredUnits[Number(e.target.id.split('.')[0])];
```

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/index.tsx
> +      group: data.group,
Деструкуризация

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/index.tsx
> +                    rangeValues[i]
Это очень сложно читать тут. Вынеси в отдельный метод

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/styled.tsx
> +  //position: relative;
коммент

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/styled.tsx
> +  //width: 100%;
коммент

2022-05-08 18:50 UTC, FerunelliW commented on src/components/ReductionTable/styled.tsx
> +    //justify-content: center;
комменты

2022-05-08 18:50 UTC, FerunelliW commented on src/data/measurement/groups/effects.ts
> +    });
```suggestion
    const res = await api.post('/measurement/group/', payload);
```

2022-05-08 18:50 UTC, FerunelliW commented on src/pages/Reductions/index.tsx
> +  const selected = useStore($selectedGroupStore);
```suggestion
  const selectedGroup = useStore($selectedGroupStore);
```

2022-05-08 18:50 UTC, FerunelliW commented on src/pages/Reductions/index.tsx
> +            title: 'Единицы измерения',
Давай в крошки собирать данные из файла, который у нас со всеми ссылками. Так нам надо будет поменять название только в одном файле, а путь только в двух, а не бегать по всему проекту

2022-05-08 18:50 UTC, FerunelliW commented on src/ui-kit/RangeInput/index.tsx
> +    setValue(`min`, innerValue ? innerValue.minValue : '');
```suggestion
    setValue(`min`, innerValue?.minValue ?? '');
```

2022-05-08 18:50 UTC, FerunelliW commented on src/ui-kit/RangeInput/index.tsx
> +    setValue(`max`, innerValue ? innerValue.maxValue : '');
Same

2022-05-08 18:50 UTC, FerunelliW commented on src/ui-kit/RangeInput/index.tsx
> +  // console.log(value);
Поудаляй комменты

2022-05-08 18:50 UTC, FerunelliW commented on src/ui-kit/RangeInput/index.tsx
> +            handleSubmit({
Вынести в отдельную функцию

2022-05-08 18:50 UTC, FerunelliW commented on src/ui-kit/RangeInput/index.tsx
> +              maxValue: watch(`max`) ? Number(watch(`max`)) : innerValue?.maxValue,
watch возвращает подписку. Она тебе не нужна. Найди метод единого взятия значения

2022-05-08 18:50 UTC, FerunelliW commented on src/ui-kit/RangeInput/index.tsx
> +            setValue(`min`, '');
Мне кажется есть способ лучше. Например попробуй поискать метод resetFields/resetValues/еще какой-то ресет

2022-05-09 10:04 UTC, Nerunelli commented on src/ui-kit/RangeInput/index.tsx
> +              maxValue: watch(`max`) ? Number(watch(`max`)) : innerValue?.maxValue,
почему не нужна

2022-05-09 10:12 UTC, Nerunelli commented on src/pages/Reductions/index.tsx
> +            title: 'Единицы измерения',
потом посмотрю

2022-05-09 10:32 UTC, FerunelliW approved these changes

2022-05-09 15:26 UTC, merged

2022-05-09 15:26 UTC, FerunelliW approved these changes